<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="21769" started-at="2014-09-10T10:10:09Z" finished-at="2014-09-10T10:10:31Z">
    <groups>
    </groups>
    <test name="tests" duration-ms="5375" started-at="2014-09-10T10:10:09Z" finished-at="2014-09-10T10:10:15Z">
      <class name="tests.NewTest">
        <test-method status="PASS" signature="f()[pri:0, instance:tests.NewTest@5e64fe]" name="f" duration-ms="5360" started-at="2014-09-10T15:40:09Z" finished-at="2014-09-10T15:40:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
      </class> <!-- tests.NewTest -->
    </test> <!-- tests -->
    <test name="tests1" duration-ms="16364" started-at="2014-09-10T10:10:15Z" finished-at="2014-09-10T10:10:31Z">
      <class name="tests.NewTest1">
        <test-method status="FAIL" signature="test()[pri:0, instance:tests.NewTest1@ba30aa]" name="test" duration-ms="16363" started-at="2014-09-10T15:40:15Z" finished-at="2014-09-10T15:40:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Email field is missing]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Email field is missing
	at org.testng.Assert.fail(Assert.java:94)
	at tests.NewTest1.test(NewTest1.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- tests.NewTest1 -->
    </test> <!-- tests1 -->
  </suite> <!-- Suite1 -->
</testng-results>
